version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez satış tablosu 
        columns:
          - name: date_date
            description: satın alma tarihi
          - name: orders_id
            description: her siparişin benzersiz kimliği
          - name: pdt_id
            description: her ürünün benzersiz kimliği
          - name: revenue
            description: siparişten elde edilen toplam gelir
          - name: quantity
            description: sipariş edilen ürün miktarı
      - name: product
        identifier: raw_gz_product
        description: Greenweez ürün tablosu
        columns:
          - name: products_id
            description: her ürünün benzersiz kimliği
          - name: purchSE_PRICE
            description: ürün fiyatı
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: nakliye tablosu
        columns:
          - name: orders_id
            description: sipariş kimliği
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: gönderim ücreti
          - name: logcost
            description: lojistik maliyeti
          - name: ship_cost
            description: kargo maliyeti
