version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez satış tablosu/her orders_id'de bulunan product_id için bir satırımız var
        columns:
          - name: date_date
            description: satın alma tarihi
          - name: orders_id
            description: Ship tablosu için dış anahtar (foreign key).
          - name: pdt_id
            description: Product tablosu için dış anahtar (foreign key).
          - name: revenue
            description: Müşteri tarafından ürünü satın almak için ödenen tutar. Gelir = Miktar * Satış Fiyatı.
          - name: quantity
            description: Belirli bir sipariş için satın alınan ürün miktarı.
        tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns:
                  - orders_id
                  - pdt_id  
          

      - name: product
        identifier: raw_gz_product
        description: Greenweez ürün tablosu.
        columns:
          - name: products_id
            description: her ürünün benzersiz kimliği/Birincil anahtar (Primary key).
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: Ürünün alış (satın alma) fiyatı.
            
      - name: ship
        identifier: raw_gz_ship
        description: Greenweez siparişleri için gönderi (kargo) verileri.
        columns:
          - name: orders_id
            description: sipariş kimliği/Birincil anahtar (Primary key).
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: Müşterinin kargo için ödediği ücret.
          - name: logcost
            description: Dağıtım merkezi/depodaki paketi hazırlama maliyeti (lojistik maliyeti).
          - name: ship_cost
            description: Greenweez'in taşıyıcıya/lojistik sağlayıcıya ödediği kargo maliyeti.
